FROM liyuanbiao/tuic:latest AS builder
FROM alpine:latest AS dist

COPY --from=builder /usr/local/bin/tuic-client /usr/local/bin/

RUN set -ex \
    && chmod +x /usr/local/bin/tuic-client \
    && apk update \
    && apk add tzdata ca-certificates \
    && rm -rf /var/cache/apk/*

VOLUME [ "/etc/tuic/" ]

ENTRYPOINT [ "/usr/local/bin/tuic-client" ]

CMD [ "-c", "/etc/tuic/client.json" ]
